export { AdvancedPOSManagement as POSDashboard } from './POSDashboard'
export { EnhancedPOSTerminal as POSTerminal } from './POSTerminal'
export { POSSessionList } from './POSSessionList'
export { POSSessionDetail } from './POSSessionDetail'
export { POSTransactionList } from './POSTransactionList'
export { POSTransactionDetail } from './POSTransactionDetail'
export { POSPaymentList } from './POSPaymentList'
export { POSReceiptList } from './POSReceiptList'
export { POSRegisterManagement } from './POSRegisterManagement'
export { POSCashDrawerManagement } from './POSCashDrawerManagement'
export { POSProductManagement } from './POSProductManagement'
export { POSCustomerManagement } from './POSCustomerManagement'
export { POSDiscountManagement } from './POSDiscountManagement'
export { POSTaxManagement } from './POSTaxManagement'
export { POSShiftManagement } from './POSShiftManagement'
export { POSEmployeeManagement } from './POSEmployeeManagement'
